### ISSUE TITLE
Conda-forge recipe

### ISSUE THREAD

**Issue by banesullivan** [Kitware/ipyvtk-simple#20]

**Comment by rabernat** [comment]
As far as I can tell ipyftk-simple is the only [pyvista optional dependency](https://docs.pyvista.org/getting-started/installation.html) that is not on conda forge.

**Comment by banesullivan** [comment]
I'm going to change the package name per #19 before submitting the recipe

**Comment by banesullivan** [comment]
Done. See https://github.com/conda-forge/ipyvtklink-feedstock
