### ISSUE TITLE
weakref looses ren_win

### ISSUE THREAD

**Issue by skoudoro** [Kitware/ipyvtk-simple#23]
Hi @banesullivan,

First, Thank you for this nice extension. It will be really useful for us. 

I try to run the code below in a Jupyter notebook and I lose the interaction.  As you can see, I just copied your example and move the rendering part in a function.

Do you have any idea of what's going on? what do we lose communication?  Thank you for your feedback

```python
# Create some data
cylinder = vtk.vtkCylinderSource()
cylinder.SetResolution(8)
mapper = vtk.vtkPolyDataMapper()
mapper.SetInputConnection(cylinder.GetOutputPort())
actor = vtk.vtkActor()
actor.SetMapper(mapper)

def show(act):
    # Set up render window
    ren = vtk.vtkRenderer()
    ren_win = vtk.vtkRenderWindow()
    ren_win.SetOffScreenRendering(1)
    ren_win.SetSize(600, 600)
    ren_win.AddRenderer(ren)
    iren = vtk.vtkRenderWindowInteractor()
    iren.SetRenderWindow(ren_win)
    style = vtk.vtkInteractorStyleTrackballCamera()
    iren.SetInteractorStyle(style)

    # Add actor to scene
    ren.AddActor(act)
    ren.ResetCamera()

    # Display
    return ViewInteractiveWidget(ren_win)

show(actor)
```

**Comment by skoudoro** [comment]
it might be due to the `weakref`, we might lose the `ren_win`. I am not sure. but if I make `ren_win` global, it works as expected. So, it might be good to have an option to "strengthen" `ren_win`. (via copy or whatever).

```python
# Create some data
cylinder = vtk.vtkCylinderSource()
cylinder.SetResolution(8)
mapper = vtk.vtkPolyDataMapper()
mapper.SetInputConnection(cylinder.GetOutputPort())
actor = vtk.vtkActor()
actor.SetMapper(mapper)

ren_win = None

def show(act):
    global ren_win
    # Set up render window
    ren = vtk.vtkRenderer()
    ren_win = vtk.vtkRenderWindow()
    ren_win.SetOffScreenRendering(1)
    ren_win.SetSize(600, 600)
    ren_win.AddRenderer(ren)
    iren = vtk.vtkRenderWindowInteractor()
    iren.SetRenderWindow(ren_win)
    style = vtk.vtkInteractorStyleTrackballCamera()
    iren.SetInteractorStyle(style)

    # Add actor to scene
    ren.AddActor(act)
    ren.ResetCamera()

    # Display
    return ViewInteractiveWidget(ren_win)

show(actor)
```

**Comment by banesullivan** [comment]
Yep, this is likely a result of the weakref and the fact that your ren_win gets garbage collected after the function exits

I'd recommend making a custom class to hold all of this rather than standalone functions.

I'll see if I can find time to look into a solution though

**Comment by banesullivan** [comment]
The solution is to always implement this sort of thing as a custom class managing references there. 

We need to stick with a weakref to make sure `ipyvtklink` doesn't prevent deletion/closing of downstream render windows (e.g. coming from PyVsita).


----

> So, it might be good to have an option to "strengthen" ren_win. (via copy or whatever).

IMO, `ipyvtklink` should stay as simple as possible and require downstream projects to implement any sort of additional, complex features. As such, making a custom class to manage this reference is what I think is the best approach.
