### ISSUE TITLE
Mouse input extremely and overly sensitive

### ISSUE THREAD

**Issue by nantille** [Kitware/ipyvtk-simple#24]
First of all, thanks for this extension. It's the only thing that interactively works in Jupyter notebooks with vtk-based libraries for some reason...

However, unlike the examples on this github page showing live interaction in a notebook, when I run any simple pyvista example in a Jupyter notebook results in uncontrollable behaviour with the mouse. If I try to orbit the camera, it goes crazy and makes big jumps. Changing mouse sensitivity in the system settings doesn't affect that behaviour. Tested on Ubuntu 20 LTS and MacOS Mojave with Jupyter notebook.

Running the same code with pyvista outside a Jupyter notebook, there's no such issue.

**Comment by denphi** [comment]
Agree, thanks for this extension. I have looked for something similar a long time ago.

I faced the same problem rendering a simple vtk model with Firefox 84.0.1 (64-bit) MacOS Big Sur, however, the notebook works perfectly fine on Chrome 87.0.4280.88 (x86_64) and Safari 14.0.2 (16610.3.7.1.9)

**Comment by banesullivan** [comment]
I think this is an issue depending on the browser. I have only tested this within Chrome. 

I will see if I can add a fix or a way to dial down the sensitivity, but it may take a while before I can get back to this.

**Comment by nantille** [comment]
I forgot to mention that on both Ubuntu and MacOs, I used Firefox (v84) like @denphi . Currently ipyvtk is not usable as it is because of this issue. Any temporary quick fix is appreciated, or if it's not too much work, exposing a method to control this in the python API. Thanks!

**Comment by denphi** [comment]
Added a PR with a possible solution #25

**Comment by nantille** [comment]
Great! Thank you @denphi. I tested it and it works.

**Comment by banesullivan** [comment]
Merged, tagged `0.1.4`, and released. Should be on PyPI soon
