### ISSUE TITLE
Example notebooks does not show widgets

### ISSUE THREAD

**Issue by jorgensd** [Kitware/ipyvtk-simple#27]
The notebooks currently show:
```
Error displaying widget: model not found
```
when running `docker run -p 8878:8878 ipyvtk_simple jupyter lab --port=8878 --no-browser --ip=0.0.0.0 --allow-root` (using the updated Dockerfile from #26).

**Comment by banesullivan** [comment]
Seems like a continuation of #7

I can reproduce and I am working to resolve this.
