### ISSUE TITLE
Improve interactive performance

### ISSUE THREAD

**Issue by banesullivan** [Kitware/ipyvtk-simple#3]
Performance on mybinder is very poor. We need to improve the performance and set up render timers that will prevent overloads of frames trying to stream back to the client

**Comment by davidbrochart** [comment]
You probably want to use a debouncer/throttler. Please have a look at the [ipywidgets documentation](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html#Debouncing), and at [this notebook](https://github.com/martinRenou/ipycanvas/blob/master/examples/mapping.ipynb) for an example usage.

**Comment by banesullivan** [comment]
Ah thanks, @davidbrochart! This was pretty easy to implement. Would you have a second to look at the implementation in #8 and provide any feedback?

I'm currently launching that branch on my binder to see if it is better (it was a bit better on Docker locally)
