### ISSUE TITLE
Widget unusable slow when using on VSCode with Remote-SSH Plugin

### ISSUE THREAD

**Issue by tjahn** [Kitware/ipyvtk-simple#31]
Hello,

I am running VSCode and use pyvista with the ipyvtk backend to open an interactive widget showing a sphere.
It works fine, if I work in a local project. But when trying to use a project lying on a remote server using the Remote-SSH plugin, the widget becomes unusable laggy. It works fine, when starting a jupyter kernel on the remote host and connecting to it from a local VSCode project though.

This is the code I am using to create the widget:

```python
import pyvista as pv
pv.start_xvfb() #if X11 DISPLAY is available on the server you may remove this line
sphere = pv.Sphere()
plotter = pv.Plotter(notebook=True)
plotter.add_mesh(sphere)
plotter.show(use_ipyvtk=True)
```

I also created an issue on vscode microsoft/vscode#121519 with a more detailed explanation.

**Comment by banesullivan** [comment]
This is typically a result of a network connection issue. microsoft/vscode#121519  is closed, so also closing this
