### ISSUE TITLE
Should PyVista be a hard depend?

### ISSUE THREAD

**Issue by banesullivan** [Kitware/ipyvtk-simple#6]
I can't make up my mind on what to do with the `iPlotter` class and where it would be best to maintain that. If keeping `iPlotter` here, we may want to make PyVista an optional dependency and have that class as a mixin. This would simplify using this widget with ParaView where we do not want pip or conda to install a separate VTK or we don't need/want PyVista and its depends in the virtual environment at all

cc @akaszynski and @GuillaumeFavelier

**Comment by banesullivan** [comment]
@marcomusy, you may also find this new widget useful 😉

**Comment by GuillaumeFavelier** [comment]
Why not maintain the iPlotter in a standalone project in the pyvista organization? Similarly to pyvistaqt, it would require pyvista as a hard dependency plus `ipyvtk-simple` for the `ViewInteractiveWidget` (which does not seem to have any dependency to `pyvista`).

**Comment by banesullivan** [comment]
I like that idea, @GuillaumeFavelier! Then when [`ipyvtk`](https://github.com/Kitware/ipyvtk) is released, we can switch the dependency from `ipyvtk-simple` to that more polished toolkit over in the PyVista project.

For now, I'd like to clean this code up and get it on PyPI so I may keep `iPlotter` in here for that release to gain some traction then phase it out as we make something under the PyVista umbrella.

also, does anyone have other name suggestions for `iPlotter`?

**Comment by GuillaumeFavelier** [comment]
I'm terrible at naming things :sweat_smile:

**Comment by akaszynski** [comment]
> Why not maintain the iPlotter in a standalone project in the pyvista organization

That would be great provided kitware is fine with that.

+1 for having pyvista as a hard dependency.

`iPlotter` isn't PEP8, so I'm leaning for `RemotePlotter` or `StreamPlotter`.  Like @GuillaumeFavelier, my naming skills are often lacking, and people are still suffering from having to type out `BackgroundPlotter`...

**Comment by banesullivan** [comment]
I'm actually thinking it may be worth doing away with `iPlotter` and using this directly in the `pyvista.Plotter.show` method, replacing what we have for `panel`. This would make it far easier to adopt and lower the burden for new users trying to figure out how to plot in Jupyter when all the examples use a `Plotter`.

**Comment by akaszynski** [comment]
That's a better idea.  We should make the interface on the `pyvista` side as light as possible to avoid having to update `pyvista` for changes with `ipyvtk`.

**Comment by GuillaumeFavelier** [comment]
I would still suggest to keep things separated. Call me biased but after using Linux for a while and embracing the KISS philosophy, I like when something does only one job and does it well instead of having a swiss army knife that does everything. I say that for the vanilla `pyvista` repo's sake too, this could avoid increasing it's complexity and maybe even simplify it.

On the other hand, it means more projects to maintain and this can also be confusing from a user perspective (although a good documentation can help with that IMO).

That being said, I understand your point of view and I'll follow your decision guys :+1:

**Comment by banesullivan** [comment]
That's a really good point, @GuillaumeFavelier. I too like to have things separated with clear intention/focus - each tool being one clear part of the toolkit to reduce complexity and potential errors from overlapping features and unclear dependency graphs. Plus this code is very much still in an alpha stage, so it would be adding potentially unstable (and untested code) directly to PyVsita.

However, many users might find that separation confusing which would limit our ability to have a clear and simple toolkit for people to utilize.

I may give it a go to see what it would take to incorporate this into PyVista. My hope is that it can be a few-liner under a bare try/except in the `Plotter.show()` method with a few minor changes to how we set up the Plotter under the hood. If so, hopefully, the complexity concern isn't too much and we can balance the swiss army knife and KISS philosophies to create something impactful for both PyVista users and the general community.
